### ISSUE TITLE
请问部分数据淘汰原因是什么？

### ISSUE THREAD

**Issue by DumoeDss** [CanvaChen/llm-dataset-chinese-poetry#1]
看到描述里说：

> 五代诗词：花间集 少数淘汰；南唐二主词 淘汰1首（《谢新恩·樱花落尽春将困》缺十二字）
诗经 少数淘汰
全唐诗：唐诗三百首 少数淘汰

请问是什么原因？

以及全唐诗与宋词两个文件夹中只看到唐诗三百首与宋词三百首，其他部分是还没有处理吗？
另外建议把数据清洗代码附上，可以一起处理~

**Comment by CanvaChen** [comment]
1. 淘汰的主要原因有：句子里有缺字；个别文字不在字库无法正常显示；内容含特殊标点符号等
2. 全唐诗与宋词剩余部分确实还没处理，有空了再补上
3. 结合手工修正，现已将之前淘汰的内容补回去

@DumoeDss
